//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 01:35:25 PM CET 
//


package be.liir.SpRL2012.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.liir.SpRL2012.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.liir.SpRL2012.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RELATION }
     * 
     */
    public RELATION createRELATION() {
        return new RELATION();
    }

    /**
     * Create an instance of {@link LANDMARK }
     * 
     */
    public LANDMARK createLANDMARK() {
        return new LANDMARK();
    }

    /**
     * Create an instance of {@link CONTENT }
     * 
     */
    public CONTENT createCONTENT() {
        return new CONTENT();
    }

    /**
     * Create an instance of {@link SPATIALINDICATOR }
     * 
     */
    public SPATIALINDICATOR createSPATIALINDICATOR() {
        return new SPATIALINDICATOR();
    }

    /**
     * Create an instance of {@link SENTENCE }
     * 
     */
    public SENTENCE createSENTENCE() {
        return new SENTENCE();
    }

    /**
     * Create an instance of {@link TRAJECTOR }
     * 
     */
    public TRAJECTOR createTRAJECTOR() {
        return new TRAJECTOR();
    }

    /**
     * Create an instance of {@link DOC }
     * 
     */
    public DOC createDOC() {
        return new DOC();
    }

}
