//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 01:35:25 PM CET 
//


package be.liir.SpRL2012.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import be.liir.SpRL.model.Containable;
import be.liir.SpRL.model.WithContent;
import be.liir.SpRL.model.WithIdentifier;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CONTENT"/>
 *         &lt;element ref="{}TRAJECTOR" maxOccurs="unbounded"/>
 *         &lt;element ref="{}LANDMARK" maxOccurs="unbounded"/>
 *         &lt;element ref="{}SPATIAL_INDICATOR" maxOccurs="unbounded"/>
 *         &lt;element ref="{}RELATION" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content",
    "trajector",
    "landmark",
    "spatialindicator",
    "relation"
})
@XmlRootElement(name = "SENTENCE")
public class SENTENCE implements Containable{

    @XmlElement(name = "CONTENT", required = true)
    protected CONTENT content;
    @XmlElement(name = "TRAJECTOR", required = true)
    protected List<TRAJECTOR> trajector;
    @XmlElement(name = "LANDMARK", required = true)
    protected List<LANDMARK> landmark;
    @XmlElement(name = "SPATIAL_INDICATOR", required = true)
    protected List<SPATIALINDICATOR> spatialindicator;
    @XmlElement(name = "RELATION", required = true)
    protected List<RELATION> relation;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link CONTENT }
     *     
     */
    public CONTENT getCONTENT() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTENT }
     *     
     */
    public void setCONTENT(CONTENT value) {
        this.content = value;
    }

    /**
     * Gets the value of the trajector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trajector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRAJECTOR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRAJECTOR }
     * 
     * 
     */
    public List<Containable> getTRAJECTOR() {
        if (trajector == null) {
            trajector = new ArrayList<TRAJECTOR>();
        }
        List<Containable> newList = new ArrayList<Containable>();
        newList.addAll(trajector);
        return newList;
    }

    /**
     * Gets the value of the landmark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the landmark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLANDMARK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LANDMARK }
     * 
     * 
     */
    public List<Containable> getLANDMARK() {
        if (landmark == null) {
            landmark = new ArrayList<LANDMARK>();
        }
        List<Containable> newList = new ArrayList<Containable>();
        newList.addAll(landmark);
        return newList;
    }

    /**
     * Gets the value of the spatialindicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatialindicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPATIALINDICATOR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPATIALINDICATOR }
     * 
     * 
     */
    public List<Containable> getSPATIALINDICATOR() {
        if (spatialindicator == null) {
            spatialindicator = new ArrayList<SPATIALINDICATOR>();
        }
        List<Containable> newList = new ArrayList<Containable>();
        newList.addAll(spatialindicator);
        return newList;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRELATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RELATION }
     * 
     * 
     */
    public List<RELATION> getRELATION() {
        if (relation == null) {
            relation = new ArrayList<RELATION>();
        }
        return this.relation;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

	public String getContent() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setContent(String content) {
		// TODO Auto-generated method stub
		
	}

}
